### ISSUE TITLE
Phone dial up activity dose not open 

### ISSUE THREAD

**Issue by wahrez** [hamidafghan/iApp#1]
Hello Sir,
As per our lesson regarding switching between activity via Inten, I have tried much time but unfortunately I could not open dial-up activity of my phone,
Here is the error code. 
![capture](https://user-images.githubusercontent.com/25291271/40589864-7c9ff588-620a-11e8-8337-2e314b859c7b.PNG)

**Comment by hamidafghan** [comment]
Please handle with try catch and log the exception.
